# Generated by Django 5.0.2 on 2024-03-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_1', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
